// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1GAiF28cdKN21M2g3tJ9KaXWOIlXPm0',
    appId: '1:515386780901:android:f942b571831b0b9543780c',
    messagingSenderId: '515386780901',
    projectId: 'scisync-65fa3',
    storageBucket: 'scisync-65fa3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnK5bUVrYGqSJ9zFroR2aVg86oC-5E1Ng',
    appId: '1:515386780901:ios:4bbef02d8b8a72c443780c',
    messagingSenderId: '515386780901',
    projectId: 'scisync-65fa3',
    storageBucket: 'scisync-65fa3.firebasestorage.app',
    iosBundleId: 'com.example.scisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuu0Gq7jIjlmOznahZA7maKGjiVsp7rtk',
    appId: '1:515386780901:web:31de4782cd413d0943780c',
    messagingSenderId: '515386780901',
    projectId: 'scisync-65fa3',
    authDomain: 'scisync-65fa3.firebaseapp.com',
    storageBucket: 'scisync-65fa3.firebasestorage.app',
  );
}
